version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Bundle Size
          command: yarn bundlesize
      - store_test_results:
          path: test-results
      - run:
          name: Publish Canary
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
            npm run ci:release:canary
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules