version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.7.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - store_test_results:
          path: test-results
#      - run:
#          name: Publish Canary Version
#          command: yarn ci:release:canary
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules